# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd energy-grid-employee
    npm install -g @angular/cli
    npm install
    npm install typescript@">=3.6.4 <3.9.0" 
    ng update --all --force
    ng build
  displayName: 'npm install and build'
- script: |
    cd energy-grid-employee
    ng build --prod
    docker build -t $(DOCKER_USER)/$(CI_PROJECT_NAME) .
    docker tag $(DOCKER_USER)/$(CI_PROJECT_NAME) $(DOCKER_USER)/$(CI_PROJECT_NAME):$(Build.SourceVersion)
    docker login -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
    docker push $(DOCKER_USER)/$(CI_PROJECT_NAME)
  displayName: 'create and push docker image'
